### ISSUE TITLE
Builds fine on Mac, any semirealistic sample projects?

### ISSUE THREAD

**Issue by CartBlanche** [JamesDunne/aardwolf#1]
Hi James,
  I just forked this project and using the latest version of Xamarin Studio on Mac, the *.sln builds without errors and the TestNull app seems to run fine on there too. So Mono support should work on everything from PC to iOS/Android and even PS4, I think.

I am new to the world of HttpListeners so this may be a silly question, but what would be a more realistic example of using your library, rather than the TestNull sample?

Thanks.

**Comment by JamesDunne** [comment]
I had developed a sample project in tandem with this: rest0-api, also found here on my github account. I've since abandoned that project but I believe I left it in working order. aardwolf is just the low level HTTP listener (aka server) that hosts the web service.

You can make virtually any web service or even full web site based on aardwolf. The idea was to move away from using IIS as a host and be completely self-contained as a single executable process, only relying on the .NET framework and the underlying OS to remove all overhead and serve requests in an asynchronous and efficient manner.

**Comment by CartBlanche** [comment]
Thanks for the clarification. I'll take a look at rest0-api.

D.
